Do printer
cAfton/HW pull request #17
Opened 2024-10-18 21:23 UTC by cAfton

2024-10-25 15:42 UTC, Yurii-Vipshovsky requested changes
логіку видалення однозначно переписати

2024-10-25 15:42 UTC, Yurii-Vipshovsky commented on homeworks/Homework3/homework_Queue/Printer/Printer.cpp
> +	Client* newArr = new Client[size + 1];
Мені здається чи ти просто так постійно збільшуєш розмір черги, не зважаючи на те скільки в неї елементів та скільки вільного місця

2024-10-25 15:42 UTC, Yurii-Vipshovsky commented on homeworks/Homework3/homework_Queue/Printer/Printer.cpp
> +		throw invalid_argument("error while poping");
Є й інші типи помилок, тут вприницпі не було аргументів у методі, тому такий тип помилки трохи недоречний

2024-10-25 15:42 UTC, Yurii-Vipshovsky commented on homeworks/Homework3/homework_Queue/Printer/Printer.cpp
> +		start++;
Геніально, тобто якщо взяти твою програму і запхати в принтер реальний з 10мб пам'яті, то за 2 дня вона заб'ється і треба буде твій принтер нести в сервіс

2024-10-26 08:55 UTC, Inazer commented on homeworks/Homework3/homework_Queue/Printer/Printer.cpp
> +		start++;
Ну да... Як можна таке зробити

2024-10-27 13:11 UTC, merged